### ISSUE TITLE
interested in integrating with grl

### ISSUE THREAD

**Issue by ahundt** [fferri/v_repPlusPlus#1]
Hey,

I'm interested in integrating your C++ plugin framework with my [grl](github.com/ahundt/grl) library because it looks very clean and well written! However, there are two issues I'd appreciate your help with:

1. Might I suggest the [Apache 2.0](www.apache.org/licenses/LICENSE-2.0.html) license? 
    - None of the projects can be used legally until they have a license.
    - Here is a [very short bulleted summary of what Apache 2 means](https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)), it is open much like BSD/MIT. 
2. There are a bunch of different components in https://github.com/fferri/ and I'm not sure how they fit together. I see the generator, this repo, and I think I saw a library manager. Is there an overview somewhere?

Thanks!

**Comment by fferri** [comment]
The sources already have a license (BSD-style) header.

The project is not complete yet. What is missing is integration with a logger, because logging is everywhere and right now is poorly done (just the DBG macro in https://github.com/fferri/v_repExtCustomUI/blob/master/debug.h), and a C++ wrapper for each V-REP API function, like it has been (partially) done in https://github.com/fferri/v_repStubsGen/blob/master/cpp/stubs.cpp#L46 which would allow you to write more concise code, e.g.:
```
try {
    int handle = simGetObjectHandle("foo");
    std::string val = simGetObjectStringParameter(handle, param_id);
    // ...
    return true;
} catch(std::exception &ex) {
    logger->error(ex.what());
    return false;
}
```
(or even drop the `try { ... } catch(...) { ... }` thing if we want to throw an exception in case of error)
instead of:
```
int handle = simGetObjectHandle("foo");
if(handle == -1) {
    logger->error("foo object does not exist");
    return false;
}
int val_len;
char *val_sz = simGetObjectStringParameter(handle, param_id, &val_len);
if(!val_sz) {
    logger->error("param not found");
    return false;
}
std::string val(val_sz, val_len);
// ...
return true;
```

i.e. checking the "magic" return value for any error condition after each V-REP API call.

These wrapper functions would sit in the `vrep` namespace, so it is still possible to call the original function with `::simGetObjectHandle`.


After this has been done, I can also integrate this C++ framework with [v_repStubsGen](https://github.com/fferri/v_repStubsGen) so that it will generate C++ methods of the `vrep::Plugin` class, instead of C functions like it is doing now.

By the way, what is this library manager you are talking about?

**Comment by ahundt** [comment]
oh for the logger I suggest you use https://github.com/gabime/spdlog, it is small, header only, fast, the API looks identical to what you described, and you can have it run in a separate thread with one line. There are lots of spdlog logger examples in grl (in addition to other utilities like vrep to eigen conversion), plus an installer for both grl and spdlog is in https://github.com/ahundt/robotics_setup.

> By the way, what is this library manager you are talking about?

Perhaps I misunderstood what bundle deps does? I was guessing it helps v-rep find all the plugins you build.

**Comment by fferri** [comment]
That is a general purpose tool for release engineering, not specific to V-REP (but will be used in V-REP's releng)

**Comment by fferri** [comment]
This issue was moved to CoppeliaRobotics/v_repPlusPlus#1
